apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: {{ .Chart.Name }}
